# Generated by Django 5.2.1 on 2025-05-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrucao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trator',
            old_name='equipamnto_trator',
            new_name='equipamento_trator',
        ),
    ]
