# Generated by Django 5.2.1 on 2025-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrucao', '0002_rename_equipamnto_trator_trator_equipamento_trator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_fincionario', models.IntegerField()),
                ('nome_funcionario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instrutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_instrutor', models.IntegerField()),
                ('nome_instrutor', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='caminhao',
            name='id',
        ),
        migrations.AddField(
            model_name='caminhao',
            name='id_caminhao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
