# Generated by Django 5.2.1 on 2025-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrucao', '0003_funcionario_instrutores_remove_caminhao_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colhedora',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lider',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trator',
            name='id',
        ),
        migrations.AddField(
            model_name='colhedora',
            name='id_colhedora',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lider',
            name='id_lider',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trator',
            name='id_trator',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
