from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

class Caminhao(models.Model):
    data = models.DateField()
    hora = models.TimeField()
    mi = models.IntegerField() 
    ni = models.CharField(max_length=255)  
    mc = models.IntegerField() 
    nc = models.CharField(max_length=255) 
    equip = models.IntegerField() 
    ls = models.CharField(max_length=255) 
    hs = models.TimeField()  
    kms = models.FloatField() 
    lc = models.CharField(max_length=255)  
    hc = models.TimeField()  
    kmc = models.FloatField()  
    vg = models.CharField(max_length=60) 
    md = models.FloatField()  

    avaliacao_om = models.CharField(max_length=7)
    avaliacao_dg = models.CharField(max_length=7)
    avaliacao_aa = models.CharField(max_length=7)
    avaliacao_or = models.CharField(max_length=7)
    avaliacao_caminhao = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    observacoes = models.TextField()


class Colhedora(models.Model):
    data2 = models.DateField()
    hora2 = models.TimeField()
    mit = models.IntegerField()
    nit = models.CharField(max_length=255)
    mct = models.IntegerField()
    nct = models.CharField(max_length=255)
    equipt = models.IntegerField()
    hsa = models.TimeField()
    hca = models.TimeField()
    hori = models.FloatField()
    horif = models.FloatField()
    cldfrente = models.IntegerField()
    avaliacao_om2 = models.IntegerField()
    avaliacao_bord2 = models.IntegerField()
    avaliacao_aut2 = models.IntegerField()
    avaliacao_op2 = models.IntegerField()
    avaliacao_pcb = models.IntegerField()
    avaliacao_pp = models.IntegerField()
    avaliacao_cb = models.IntegerField()
    avaliacao_st = models.IntegerField()
    avaliacao_vc2 = models.IntegerField()
    avaliacao_tec = models.IntegerField()
    avaliacao_sdd2 = models.IntegerField()
    avaliacao_gi = models.IntegerField()
    observacoes = models.TextField()

class Trator(models.Model):
    data3 = models.DateField()
    hora3 = models.TimeField()
    mit2 = models.IntegerField()
    nit2 = models.CharField(max_length=255)
    mct2 = models.IntegerField()
    nct2 = models.CharField(max_length=255)
    equipt2 = models.IntegerField()
    lsa2 = models.CharField(max_length=255)
    hsa2 = models.TimeField()
    lca2 = models.CharField(max_length=255)
    hca2 = models.CharField(max_length=255)
    hori2 = models.FloatField()
    horif2 = models.FloatField()
    avaliacao_opm = models.IntegerField()
    avaliacao_bordo = models.IntegerField()
    avaliacao_autz = models.IntegerField()
    avaliacao_opo = models.IntegerField()
    avaliacao_inst = models.IntegerField()
    avaliacao_rot = models.IntegerField()
    avaliacao_sdono = models.IntegerField()
    avaliacao_tm = models.IntegerField()
    avaliacao_te = models.IntegerField()
    avaliacao_vct = models.IntegerField()
    avaliacao_sc = models.IntegerField()
    avaliacao_pl = models.IntegerField()
    observacoes = models.TextField()


class Lider(models.Model):
    data4 = models.DateField()
    hora4 = models.TimeField()
    mit3 = models.IntegerField()
    nit3 = models.CharField(max_length=255)
    mctl3 = models.IntegerField()
    nctl3 = models.CharField(max_length=255)
    ldrfrente = models.IntegerField()
    fazenda = models.CharField(max_length=255)
    unidade = models.CharField(max_length=255)  # corrigido
    avaliacao_lider1 = models.IntegerField()
    avaliacao_lider2 = models.IntegerField()
    avaliacao_lider3 = models.IntegerField()
    avaliacao_lider4 = models.IntegerField()
    avaliacao_lider5 = models.IntegerField()
    avaliacao_lider6 = models.IntegerField()
    avaliacao_lider7 = models.IntegerField()    
    observacoes = models.TextField(max_length=255)

